- name: mysqlplay - installing mysql
  hosts: target2-mgmt
  remote_user: remoteadmin
  tasks:
    - name: install mysql
      apt:
        name: mysql-server
        state: present
        update_cache: yes
        
    - name: enable ufw
      apt:
        name: ufw
        state: present
        
    - name: allow ssh
      ufw:
        rule: allow
        port: 22
        proto: tcp
        
    - name: allow mysql
      ufw:
        rule: allow
        port: 3306
        proto: tcp
